INSERT INTO Country
  ( CountryName, CountryCode, Currency, CapitalCity )
  SELECT *
  FROM (
VALUES 
( 'Anguilla', 'AIA', 'XCD', 'The Valley' ),
( 'Guatemala', 'GTM', 'GTQ', 'Guatemala City' ),
  ( 'Gambia', 'GMB', 'GMD', 'Banjul' ),
  ( 'Mexico', 'MEX', 'MXN', 'Mexico City' ),
  ( 'Malawi', 'MWI', 'MWK', 'Lilongwe' ),
  ( 'Pitcairn Islands', 'PCN', 'NZD', 'Adamstown' ),
  ( 'Argentina', 'ARG', 'ARS', 'Buenos Aires' ),
  ( 'Guam', 'GUM', 'USD', 'Hagåtña' ),
  ( 'Bulgaria', 'BGR', 'BGN', 'Sofia' ),
  ( 'Dominica', 'DMA', 'XCD', 'Roseau' ),
  ( 'United Kingdom', 'GBR', 'GBP', 'London' ),
  ( 'Micronesia', 'FSM', 'USD', 'Palikir' ),
  ( 'Palestine', 'PSE', 'JOD', 'Ramallah' ),
  ( 'Curaçao', 'CUW', 'ANG', 'Willemstad' ),
  ( 'Rwanda', 'RWA', 'RWF', 'Kigali' ),
  ( 'Hong Kong', 'HKG', 'HKD', 'City of Victoria' ),
  ( 'Uzbekistan', 'UZB', 'UZS', 'Tashkent' ),
  ( 'China', 'CHN', 'CNY', 'Beijing' ),
  ( 'Cyprus', 'CYP', 'EUR', 'Nicosia' ),
  ( 'Aruba', 'ABW', 'AWG', 'Oranjestad' ),
  ( 'Réunion', 'REU', 'EUR', 'Saint-Denis' ),
  ( 'South Korea', 'KOR', 'KRW', 'Seoul' ),
  ( 'Antarctica', 'ATA', '', '' ),
  ( 'Somalia', 'SOM', 'SOS', 'Mogadishu' ),
  ( 'Lebanon', 'LBN', 'LBP', 'Beirut' ),
  ( 'Guinea', 'GIN', 'GNF', 'Conakry' ),
  ( 'Tajikistan', 'TJK', 'TJS', 'Dushanbe' ),
  ( 'Malaysia', 'MYS', 'MYR', 'Kuala Lumpur' ),
  ( 'North Korea', 'PRK', 'KPW', 'Pyongyang' ),
  ( 'Sierra Leone', 'SLE', 'SLE', 'Freetown' ),
  ( 'Benin', 'BEN', 'XOF', 'Porto-Novo' ),
  ( 'Italy', 'ITA', 'EUR', 'Rome' ),
  ( 'Trinidad and Tobago', 'TTO', 'TTD', 'Port of Spain' ),
  ( 'Saudi Arabia', 'SAU', 'SAR', 'Riyadh' ),
  ( 'Costa Rica', 'CRI', 'CRC', 'San José' ),
  ( 'Serbia', 'SRB', 'RSD', 'Belgrade' ),
  ( 'Tokelau', 'TKL', 'NZD', 'Fakaofo' ),
  ( 'Mongolia', 'MNG', 'MNT', 'Ulan Bator' ),
  ( 'Brunei', 'BRN', 'SGD', 'Bandar Seri Begawan' ),
  ( 'Hungary', 'HUN', 'HUF', 'Budapest' ),
  ( 'Mozambique', 'MOZ', 'MZN', 'Maputo' ),
  ( 'Kiribati', 'KIR', 'KID', 'South Tarawa' ),
  ( 'Haiti', 'HTI', 'HTG', 'Port-au-Prince' ),
  ( 'Cambodia', 'KHM', 'KHR', 'Phnom Penh' ),
  ( 'Egypt', 'EGY', 'EGP', 'Cairo' ),
  ( 'Turkmenistan', 'TKM', 'TMT', 'Ashgabat' ),
  ( 'Oman', 'OMN', 'OMR', 'Muscat' ),
  ( 'Jamaica', 'JAM', 'JMD', 'Kingston' ),
  ( 'Azerbaijan', 'AZE', 'AZN', 'Baku' ),
  ( 'Slovakia', 'SVK', 'EUR', 'Bratislava' ),
  ( 'Belarus', 'BLR', 'BYN', 'Minsk' ),
  ( 'Vietnam', 'VNM', 'VND', 'Hanoi' ),
  ( 'United States Virgin Islands', 'VIR', 'USD', 'Charlotte Amalie' ),
  ( 'Gibraltar', 'GIB', 'GIP', 'Gibraltar' ),
  ( 'Sint Maarten', 'SXM', 'ANG', 'Philipsburg' ),
  ( 'Åland Islands', 'ALA', 'EUR', 'Mariehamn' ),
  ( 'Syria', 'SYR', 'SYP', 'Damascus' ),
  ( 'Martinique', 'MTQ', 'EUR', 'Fort-de-France' ),
  ( 'Greenland', 'GRL', 'DKK', 'Nuuk' ),
  ( 'Honduras', 'HND', 'HNL', 'Tegucigalpa' ),
  ( 'Tunisia', 'TUN', 'TND', 'Tunis' ),
  ( 'Comoros', 'COM', 'KMF', 'Moroni' ),
  ( 'Slovenia', 'SVN', 'EUR', 'Ljubljana' ),
  ( 'Switzerland', 'CHE', 'CHF', 'Bern' ),
  ( 'Guernsey', 'GGY', 'GGP', 'St. Peter Port' ),
  ( 'Myanmar', 'MMR', 'MMK', 'Naypyidaw' ),
  ( 'Paraguay', 'PRY', 'PYG', 'Asunción' ),
  ( 'Caribbean Netherlands', 'BES', 'USD', 'Kralendijk' ),
  ( 'Barbados', 'BRB', 'BBD', 'Bridgetown' ),
  ( 'Macau', 'MAC', 'MOP', '' ),
  ( 'Jordan', 'JOR', 'JOD', 'Amman' ),
  ( 'Laos', 'LAO', 'LAK', 'Vientiane' ),
  ( 'Togo', 'TGO', 'XOF', 'Lomé' ),
  ( 'Morocco', 'MAR', 'MAD', 'Rabat' ),
  ( 'Puerto Rico', 'PRI', 'USD', 'San Juan' ),
  ( 'French Guiana', 'GUF', 'EUR', 'Cayenne' ),
  ( 'Saint Pierre and Miquelon', 'SPM', 'EUR', 'Saint-Pierre' ),
  ( 'Saint Martin', 'MAF', 'EUR', 'Marigot' ),
  ( 'Estonia', 'EST', 'EUR', 'Tallinn' ),
  ( 'Indonesia', 'IDN', 'IDR', 'Jakarta' ),
  ( 'Seychelles', 'SYC', 'SCR', 'Victoria' ),
  ( 'Mali', 'MLI', 'XOF', 'Bamako' ),
  ( 'Timor-Leste', 'TLS', 'USD', 'Dili' ),
  ( 'Brazil', 'BRA', 'BRL', 'Brasília' ),
  ( 'Ghana', 'GHA', 'GHS', 'Accra' ),
  ( 'Kenya', 'KEN', 'KES', 'Nairobi' ),
  ( 'Iceland', 'ISL', 'ISK', 'Reykjavik' ),
  ( 'Madagascar', 'MDG', 'MGA', 'Antananarivo' ),
  ( 'Bangladesh', 'BGD', 'BDT', 'Dhaka' ),
  ( 'DR Congo', 'COD', 'CDF', 'Kinshasa' ),
  ( 'Zimbabwe', 'ZWE', 'ZWL', 'Harare' ),
  ( 'French Polynesia', 'PYF', 'XPF', 'Papeetē' ),
  ( 'Turkey', 'TUR', 'TRY', 'Ankara' ),
  ( 'Cape Verde', 'CPV', 'CVE', 'Praia' ),
  ( 'Dominican Republic', 'DOM', 'DOP', 'Santo Domingo' ),
  ( 'Bahamas', 'BHS', 'BSD', 'Nassau' ),
  ( 'Germany', 'DEU', 'EUR', 'Berlin' ),
  ( 'Suriname', 'SUR', 'SRD', 'Paramaribo' ),
  ( 'Tonga', 'TON', 'TOP', 'Nuku''alofa' ),
  ( 'British Indian Ocean Territory', 'IOT', 'USD', 'Diego Garcia' ),
  ( 'Saint Lucia', 'LCA', 'XCD', 'Castries' ),
  ( 'Ireland', 'IRL', 'EUR', 'Dublin' ),
  ( 'Vatican City', 'VAT', 'EUR', 'Vatican City' ),
  ( 'Colombia', 'COL', 'COP', 'Bogotá' ),
  ( 'Portugal', 'PRT', 'EUR', 'Lisbon' ),
  ( 'Faroe Islands', 'FRO', 'FOK', 'Tórshavn' ),
  ( 'São Tomé and Príncipe', 'STP', 'STN', 'São Tomé' ),
  ( 'Northern Mariana Islands', 'MNP', 'USD', 'Saipan' ),
  ( 'Jersey', 'JEY', 'JEP', 'Saint Helier' ),
  ( 'Mayotte', 'MYT', 'EUR', 'Mamoudzou' ),
  ( 'Yemen', 'YEM', 'YER', 'Sana''a' ),
  ( 'Nigeria', 'NGA', 'NGN', 'Abuja' ),
  ( 'Afghanistan', 'AFG', 'AFN', 'Kabul' ),
  ( 'Botswana', 'BWA', 'BWP', 'Gaborone' ),
  ( 'Isle of Man', 'IMN', 'IMP', 'Douglas' ),
  ( 'El Salvador', 'SLV', 'USD', 'San Salvador' ),
  ( 'Uganda', 'UGA', 'UGX', 'Kampala' ),
  ( 'Andorra', 'AND', 'EUR', 'Andorra la Vella' ),
  ( 'Turks and Caicos Islands', 'TCA', 'USD', 'Cockburn Town' ),
  ( 'Chad', 'TCD', 'XAF', 'N''Djamena' ),
  ( 'Finland', 'FIN', 'EUR', 'Helsinki' ),
  ( 'Russia', 'RUS', 'RUB', 'Moscow' ),
  ( 'Kazakhstan', 'KAZ', 'KZT', 'Astana' ),
  ( 'Svalbard and Jan Mayen', 'SJM', 'NOK', 'Longyearbyen' ),
  ( 'Venezuela', 'VEN', 'VES', 'Caracas' ),
  ( 'Monaco', 'MCO', 'EUR', 'Monaco' ),
  ( 'Senegal', 'SEN', 'XOF', 'Dakar' ),
  ( 'Nepal', 'NPL', 'NPR', 'Kathmandu' ),
  ( 'United Arab Emirates', 'ARE', 'AED', 'Abu Dhabi' ),
  ( 'Taiwan', 'TWN', 'TWD', 'Taipei' ),
  ( 'New Caledonia', 'NCL', 'XPF', 'Nouméa' ),
  ( 'Bolivia', 'BOL', 'BOB', 'Sucre' ),
  ( 'Chile', 'CHL', 'CLP', 'Santiago' ),
  ( 'Ivory Coast', 'CIV', 'XOF', 'Yamoussoukro' ),
  ( 'Libya', 'LBY', 'LYD', 'Tripoli' ),
  ( 'Peru', 'PER', 'PEN', 'Lima' ),
  ( 'Canada', 'CAN', 'CAD', 'Ottawa' ),
  ( 'France', 'FRA', 'EUR', 'Paris' ),
  ( 'Djibouti', 'DJI', 'DJF', 'Djibouti' ),
  ( 'Burundi', 'BDI', 'BIF', 'Gitega' ),
  ( 'Kosovo', 'UNK', 'EUR', 'Pristina' ),
  ( 'Denmark', 'DNK', 'DKK', 'Copenhagen' ),
  ( 'Greece', 'GRC', 'EUR', 'Athens' ),
  ( 'Czechia', 'CZE', 'CZK', 'Prague' ),
  ( 'Eritrea', 'ERI', 'ERN', 'Asmara' ),
  ( 'Namibia', 'NAM', 'ZAR', 'Windhoek' ),
  ( 'British Virgin Islands', 'VGB', 'USD', 'Road Town' ),
  ( 'Iran', 'IRN', 'IRR', 'Tehran' ),
  ( 'Equatorial Guinea', 'GNQ', 'XAF', 'Ciudad de la Paz' ),
  ( 'Mauritania', 'MRT', 'MRU', 'Nouakchott' ),
  ( 'Bahrain', 'BHR', 'BHD', 'Manama' ),
  ( 'Cocos (Keeling) Islands', 'CCK', 'AUD', 'West Island' ),
  ( 'Ethiopia', 'ETH', 'ETB', 'Addis Ababa' ),
  ( 'Zambia', 'ZMB', 'ZMW', 'Lusaka' ),
  ( 'Bosnia and Herzegovina', 'BIH', 'BAM', 'Sarajevo' ),
  ( 'Falkland Islands', 'FLK', 'FKP', 'Stanley' ),
  ( 'Grenada', 'GRD', 'XCD', 'St. George''s' ),
  ( 'Thailand', 'THA', 'THB', 'Bangkok' ),
  ( 'Romania', 'ROU', 'RON1', 'Bucharest' ),
  ( 'Saint Vincent and the Grenadines', 'VCT', 'XCD', 'Kingstown' ),
  ( 'Liberia', 'LBR', 'LRD', 'Monrovia' ),
  ( 'United States', 'USA', 'USD', 'Washington, D.C.' ),
  ( 'South Sudan', 'SSD', 'SSP', 'Juba' ),
  ( 'Bouvet Island', 'BVT', '', '' ),
  ( 'Armenia', 'ARM', 'AMD', 'Yerevan' ),
  ( 'Japan', 'JPN', 'JPY', 'Tokyo' ),
  ( 'Pakistan', 'PAK', 'PKR', 'Islamabad' ),
  ( 'Eswatini', 'SWZ', 'SZL', 'Mbabane' ),
  ( 'Liechtenstein', 'LIE', 'CHF', 'Vaduz' ),
  ( 'Israel', 'ISR', 'ILS', 'Jerusalem' ),
  ( 'American Samoa', 'ASM', 'USD', 'Pago Pago' ),
  ( 'Sri Lanka', 'LKA', 'LKR', 'Sri Jayawardenepura Kotte' ),
  ( 'South Georgia', 'SGS', 'GBP', 'King Edward Point' ),
  ( 'Albania', 'ALB', 'ALL', 'Tirana' ),
  ( 'Algeria', 'DZA', 'DZD', 'Algiers' ),
  ( 'Ukraine', 'UKR', 'UAH', 'Kyiv' ),
  ( 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'SHP', 'Jamestown' ),
  ( 'Heard Island and McDonald Islands', 'HMD', '', '' ),
  ( 'San Marino', 'SMR', 'EUR', 'City of San Marino' ),
  ( 'Cuba', 'CUB', 'CUP', 'Havana' ),
  ( 'Nauru', 'NRU', 'AUD', 'Yaren' ),
  ( 'Spain', 'ESP', 'EUR', 'Madrid' ),
  ( 'Kuwait', 'KWT', 'KWD', 'Kuwait City' ),
  ( 'Montserrat', 'MSR', 'XCD', 'Plymouth' ),
  ( 'Mauritius', 'MUS', 'MUR', 'Port Louis' ),
  ( 'Sweden', 'SWE', 'SEK', 'Stockholm' ),
  ( 'Australia', 'AUS', 'AUD', 'Canberra' ),
  ( 'Cameroon', 'CMR', 'XAF', 'Yaoundé' ),
  ( 'Ecuador', 'ECU', 'USD', 'Quito' ),
  ( 'Qatar', 'QAT', 'QAR', 'Doha' ),
  ( 'Marshall Islands', 'MHL', 'USD', 'Majuro' ),
  ( 'Poland', 'POL', 'PLN', 'Warsaw' ),
  ( 'Cayman Islands', 'CYM', 'KYD', 'George Town' ),
  ( 'South Africa', 'ZAF', 'ZAR', 'Pretoria' ),
  ( 'Wallis and Futuna', 'WLF', 'XPF', 'Mata-Utu' ),
  ( 'Samoa', 'WSM', 'WST', 'Apia' ),
  ( 'Netherlands', 'NLD', 'EUR', 'Amsterdam' ),
  ( 'Western Sahara', 'ESH', 'DZD', 'El Aaiún' ),
  ( 'Montenegro', 'MNE', 'EUR', 'Podgorica' ),
  ( 'Bhutan', 'BTN', 'INR', 'Thimphu' ),
  ( 'Malta', 'MLT', 'EUR', 'Valletta' ),
  ( 'Vanuatu', 'VUT', 'VUV', 'Port Vila' ),
  ( 'Tanzania', 'TZA', 'TZS', 'Dodoma' ),
  ( 'New Zealand', 'NZL', 'NZD', 'Wellington' ),
  ( 'Palau', 'PLW', 'USD', 'Ngerulmud' ),
  ( 'Panama', 'PAN', 'PAB', 'Panama City' ),
  ( 'Tuvalu', 'TUV', 'TVD', 'Funafuti' ),
  ( 'Fiji', 'FJI', 'FJD', 'Suva' ),
  ( 'Nicaragua', 'NIC', 'NIO', 'Managua' ),
  ( 'Kyrgyzstan', 'KGZ', 'KGS', 'Bishkek' ),
  ( 'French Southern and Antarctic Lands', 'ATF', 'EUR', 'Port-aux-Français' ),
  ( 'Latvia', 'LVA', 'EUR', 'Riga' ),
  ( 'Georgia', 'GEO', 'GEL', 'Tbilisi' ),
  ( 'Luxembourg', 'LUX', 'EUR', 'Luxembourg' ),
  ( 'Austria', 'AUT', 'EUR', 'Vienna' ),
  ( 'North Macedonia', 'MKD', 'MKD1', 'Skopje' ),
  ( 'Saint Barthélemy', 'BLM', 'EUR', 'Gustavia' ),
  ( 'Christmas Island', 'CXR', 'AUD', 'Flying Fish Cove' ),
  ( 'Solomon Islands', 'SLB', 'SBD', 'Honiara' ),
  ( 'Antigua and Barbuda', 'ATG', 'XCD', 'Saint John''s' ),
  ( 'Iraq', 'IRQ', 'IQD', 'Baghdad' ),
  ( 'Moldova', 'MDA', 'MDL', 'Chișinău' ),
  ( 'Norfolk Island', 'NFK', 'AUD', 'Kingston' ),
  ( 'Republic of the Congo', 'COG', 'XAF', 'Brazzaville' ),
  ( 'Niue', 'NIU', 'NZD', 'Alofi' ),
  ( 'Lithuania', 'LTU', 'EUR', 'Vilnius' ),
  ( 'Niger', 'NER', 'XOF', 'Niamey' ),
  ( 'Guyana', 'GUY', 'GYD', 'Georgetown' ),
  ( 'Bermuda', 'BMU', 'BMD', 'Hamilton' ),
  ( 'Gabon', 'GAB', 'XAF', 'Libreville' ),
  ( 'Cook Islands', 'COK', 'CKD', 'Avarua' ),
  ( 'Angola', 'AGO', 'AOA', 'Luanda' ),
  ( 'Norway', 'NOR', 'NOK', 'Oslo' ),
  ( 'Guadeloupe', 'GLP', 'EUR', 'Basse-Terre' ),
  ( 'Maldives', 'MDV', 'MVR', 'Malé' ),
  ( 'Belgium', 'BEL', 'EUR', 'Brussels' ),
  ( 'Croatia', 'HRV', 'EUR', 'Zagreb' ),
  ( 'Belize', 'BLZ', 'BZD', 'Belmopan' ),
  ( 'Saint Kitts and Nevis', 'KNA', 'XCD', 'Basseterre' ),
  ( 'Singapore', 'SGP', 'SGD', 'Singapore' ),
  ( 'Lesotho', 'LSO', 'LSL', 'Maseru' ),
  ( 'Uruguay', 'URY', 'UYU', 'Montevideo' ),
  ( 'Burkina Faso', 'BFA', 'XOF', 'Ouagadougou' ),
  ( 'India', 'IND', 'INR', 'New Delhi' ),
  ( 'Philippines', 'PHL', 'PHP', 'Manila' ),
  ( 'Central African Republic', 'CAF', 'XAF', 'Bangui' ),
  ( 'Sudan', 'SDN', 'SDG', 'Khartoum' ),
  ( 'Guinea-Bissau', 'GNB', 'XOF', 'Bissau' ),
  ( 'Papua New Guinea', 'PNG', 'PGK', 'Port Moresby' ),
  ( 'United States Minor Outlying Islands', 'UMI', 'USD', 'Washington DC' )
  ) AS SourceData (CountryName, CountryCode, Currency, CapitalCity)
        WHERE NOT EXISTS (
            SELECT 1
            FROM Country c
            WHERE c.CountryCode = SourceData.CountryCode
);