INSERT INTO Country
  ( CountryName, CountryCode, Currency )
  SELECT *
  FROM (
VALUES  ( 'Anguilla', 'AIA', 'XCD' ),
  ( 'Guatemala', 'GTM', 'GTQ' ),
  ( 'Gambia', 'GMB', 'GMD' ),
  ( 'Mexico', 'MEX', 'MXN' ),
  ( 'Malawi', 'MWI', 'MWK' ),
  ( 'Pitcairn Islands', 'PCN', 'NZD' ),
  ( 'Argentina', 'ARG', 'ARS' ),
  ( 'Guam', 'GUM', 'USD' ),
  ( 'Bulgaria', 'BGR', 'BGN' ),
  ( 'Dominica', 'DMA', 'XCD' ),
  ( 'United Kingdom', 'GBR', 'GBP' ),
  ( 'Micronesia', 'FSM', 'USD' ),
  ( 'Palestine', 'PSE', 'JOD' ),
  ( 'Curaçao', 'CUW', 'ANG' ),
  ( 'Rwanda', 'RWA', 'RWF' ),
  ( 'Hong Kong', 'HKG', 'HKD' ),
  ( 'Uzbekistan', 'UZB', 'UZS' ),
  ( 'China', 'CHN', 'CNY' ),
  ( 'Cyprus', 'CYP', 'EUR' ),
  ( 'Aruba', 'ABW', 'AWG' ),
  ( 'Réunion', 'REU', 'EUR' ),
  ( 'South Korea', 'KOR', 'KRW' ),
  ( 'Antarctica', 'ATA', '' ),
  ( 'Somalia', 'SOM', 'SOS' ),
  ( 'Lebanon', 'LBN', 'LBP' ),
  ( 'Guinea', 'GIN', 'GNF' ),
  ( 'Tajikistan', 'TJK', 'TJS' ),
  ( 'Malaysia', 'MYS', 'MYR' ),
  ( 'North Korea', 'PRK', 'KPW' ),
  ( 'Sierra Leone', 'SLE', 'SLE' ),
  ( 'Benin', 'BEN', 'XOF' ),
  ( 'Italy', 'ITA', 'EUR' ),
  ( 'Trinidad and Tobago', 'TTO', 'TTD' ),
  ( 'Saudi Arabia', 'SAU', 'SAR' ),
  ( 'Costa Rica', 'CRI', 'CRC' ),
  ( 'Serbia', 'SRB', 'RSD' ),
  ( 'Tokelau', 'TKL', 'NZD' ),
  ( 'Mongolia', 'MNG', 'MNT' ),
  ( 'Brunei', 'BRN', 'SGD' ),
  ( 'Hungary', 'HUN', 'HUF' ),
  ( 'Mozambique', 'MOZ', 'MZN' ),
  ( 'Kiribati', 'KIR', 'KID' ),
  ( 'Haiti', 'HTI', 'HTG' ),
  ( 'Cambodia', 'KHM', 'KHR' ),
  ( 'Egypt', 'EGY', 'EGP' ),
  ( 'Turkmenistan', 'TKM', 'TMT' ),
  ( 'Oman', 'OMN', 'OMR' ),
  ( 'Jamaica', 'JAM', 'JMD' ),
  ( 'Azerbaijan', 'AZE', 'AZN' ),
  ( 'Slovakia', 'SVK', 'EUR' ),
  ( 'Belarus', 'BLR', 'BYN' ),
  ( 'Vietnam', 'VNM', 'VND' ),
  ( 'United States Virgin Islands', 'VIR', 'USD' ),
  ( 'Gibraltar', 'GIB', 'GIP' ),
  ( 'Sint Maarten', 'SXM', 'ANG' ),
  ( 'Åland Islands', 'ALA', 'EUR' ),
  ( 'Syria', 'SYR', 'SYP' ),
  ( 'Martinique', 'MTQ', 'EUR' ),
  ( 'Greenland', 'GRL', 'DKK' ),
  ( 'Honduras', 'HND', 'HNL' ),
  ( 'Tunisia', 'TUN', 'TND' ),
  ( 'Comoros', 'COM', 'KMF' ),
  ( 'Slovenia', 'SVN', 'EUR' ),
  ( 'Switzerland', 'CHE', 'CHF' ),
  ( 'Guernsey', 'GGY', 'GGP' ),
  ( 'Myanmar', 'MMR', 'MMK' ),
  ( 'Paraguay', 'PRY', 'PYG' ),
  ( 'Caribbean Netherlands', 'BES', 'USD' ),
  ( 'Barbados', 'BRB', 'BBD' ),
  ( 'Macau', 'MAC', 'MOP' ),
  ( 'Jordan', 'JOR', 'JOD' ),
  ( 'Laos', 'LAO', 'LAK' ),
  ( 'Togo', 'TGO', 'XOF' ),
  ( 'Morocco', 'MAR', 'MAD' ),
  ( 'Puerto Rico', 'PRI', 'USD' ),
  ( 'French Guiana', 'GUF', 'EUR' ),
  ( 'Saint Pierre and Miquelon', 'SPM', 'EUR' ),
  ( 'Saint Martin', 'MAF', 'EUR' ),
  ( 'Estonia', 'EST', 'EUR' ),
  ( 'Indonesia', 'IDN', 'IDR' ),
  ( 'Seychelles', 'SYC', 'SCR' ),
  ( 'Mali', 'MLI', 'XOF' ),
  ( 'Timor-Leste', 'TLS', 'USD' ),
  ( 'Brazil', 'BRA', 'BRL' ),
  ( 'Ghana', 'GHA', 'GHS' ),
  ( 'Kenya', 'KEN', 'KES' ),
  ( 'Iceland', 'ISL', 'ISK' ),
  ( 'Madagascar', 'MDG', 'MGA' ),
  ( 'Bangladesh', 'BGD', 'BDT' ),
  ( 'DR Congo', 'COD', 'CDF' ),
  ( 'Zimbabwe', 'ZWE', 'ZWL' ),
  ( 'French Polynesia', 'PYF', 'XPF' ),
  ( 'Turkey', 'TUR', 'TRY' ),
  ( 'Cape Verde', 'CPV', 'CVE' ),
  ( 'Dominican Republic', 'DOM', 'DOP' ),
  ( 'Bahamas', 'BHS', 'BSD' ),
  ( 'Germany', 'DEU', 'EUR' ),
  ( 'Suriname', 'SUR', 'SRD' ),
  ( 'Tonga', 'TON', 'TOP' ),
  ( 'British Indian Ocean Territory', 'IOT', 'USD' ),
  ( 'Saint Lucia', 'LCA', 'XCD' ),
  ( 'Ireland', 'IRL', 'EUR' ),
  ( 'Vatican City', 'VAT', 'EUR' ),
  ( 'Colombia', 'COL', 'COP' ),
  ( 'Portugal', 'PRT', 'EUR' ),
  ( 'Faroe Islands', 'FRO', 'FOK' ),
  ( 'São Tomé and Príncipe', 'STP', 'STN' ),
  ( 'Northern Mariana Islands', 'MNP', 'USD' ),
  ( 'Jersey', 'JEY', 'JEP' ),
  ( 'Mayotte', 'MYT', 'EUR' ),
  ( 'Yemen', 'YEM', 'YER' ),
  ( 'Nigeria', 'NGA', 'NGN' ),
  ( 'Afghanistan', 'AFG', 'AFN' ),
  ( 'Botswana', 'BWA', 'BWP' ),
  ( 'Isle of Man', 'IMN', 'IMP' ),
  ( 'El Salvador', 'SLV', 'USD' ),
  ( 'Uganda', 'UGA', 'UGX' ),
  ( 'Andorra', 'AND', 'EUR' ),
  ( 'Turks and Caicos Islands', 'TCA', 'USD' ),
  ( 'Chad', 'TCD', 'XAF' ),
  ( 'Finland', 'FIN', 'EUR' ),
  ( 'Russia', 'RUS', 'RUB' ),
  ( 'Kazakhstan', 'KAZ', 'KZT' ),
  ( 'Svalbard and Jan Mayen', 'SJM', 'NOK' ),
  ( 'Venezuela', 'VEN', 'VES' ),
  ( 'Monaco', 'MCO', 'EUR' ),
  ( 'Senegal', 'SEN', 'XOF' ),
  ( 'Nepal', 'NPL', 'NPR' ),
  ( 'United Arab Emirates', 'ARE', 'AED' ),
  ( 'Taiwan', 'TWN', 'TWD' ),
  ( 'New Caledonia', 'NCL', 'XPF' ),
  ( 'Bolivia', 'BOL', 'BOB' ),
  ( 'Chile', 'CHL', 'CLP' ),
  ( 'Ivory Coast', 'CIV', 'XOF' ),
  ( 'Libya', 'LBY', 'LYD' ),
  ( 'Peru', 'PER', 'PEN' ),
  ( 'Canada', 'CAN', 'CAD' ),
  ( 'France', 'FRA', 'EUR' ),
  ( 'Djibouti', 'DJI', 'DJF' ),
  ( 'Burundi', 'BDI', 'BIF' ),
  ( 'Kosovo', 'UNK', 'EUR' ),
  ( 'Denmark', 'DNK', 'DKK' ),
  ( 'Greece', 'GRC', 'EUR' ),
  ( 'Czechia', 'CZE', 'CZK' ),
  ( 'Eritrea', 'ERI', 'ERN' ),
  ( 'Namibia', 'NAM', 'ZAR' ),
  ( 'British Virgin Islands', 'VGB', 'USD' ),
  ( 'Iran', 'IRN', 'IRR' ),
  ( 'Equatorial Guinea', 'GNQ', 'XAF' ),
  ( 'Mauritania', 'MRT', 'MRU' ),
  ( 'Bahrain', 'BHR', 'BHD' ),
  ( 'Cocos (Keeling) Islands', 'CCK', 'AUD' ),
  ( 'Ethiopia', 'ETH', 'ETB' ),
  ( 'Zambia', 'ZMB', 'ZMW' ),
  ( 'Bosnia and Herzegovina', 'BIH', 'BAM' ),
  ( 'Falkland Islands', 'FLK', 'FKP' ),
  ( 'Grenada', 'GRD', 'XCD' ),
  ( 'Thailand', 'THA', 'THB' ),
  ( 'Romania', 'ROU', 'RON' ),
  ( 'Saint Vincent and the Grenadines', 'VCT', 'XCD' ),
  ( 'Liberia', 'LBR', 'LRD' ),
  ( 'United States', 'USA', 'USD' ),
  ( 'South Sudan', 'SSD', 'SSP' ),
  ( 'Bouvet Island', 'BVT', '' ),
  ( 'Armenia', 'ARM', 'AMD' ),
  ( 'Japan', 'JPN', 'JPY' ),
  ( 'Pakistan', 'PAK', 'PKR' ),
  ( 'Eswatini', 'SWZ', 'SZL' ),
  ( 'Liechtenstein', 'LIE', 'CHF' ),
  ( 'Israel', 'ISR', 'ILS' ),
  ( 'American Samoa', 'ASM', 'USD' ),
  ( 'Sri Lanka', 'LKA', 'LKR' ),
  ( 'South Georgia', 'SGS', 'GBP' ),
  ( 'Albania', 'ALB', 'ALL' ),
  ( 'Algeria', 'DZA', 'DZD' ),
  ( 'Ukraine', 'UKR', 'UAH' ),
  ( 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'SHP' ),
  ( 'Heard Island and McDonald Islands', 'HMD', '' ),
  ( 'San Marino', 'SMR', 'EUR' ),
  ( 'Cuba', 'CUB', 'CUP' ),
  ( 'Nauru', 'NRU', 'AUD' ),
  ( 'Spain', 'ESP', 'EUR' ),
  ( 'Kuwait', 'KWT', 'KWD' ),
  ( 'Montserrat', 'MSR', 'XCD' ),
  ( 'Mauritius', 'MUS', 'MUR' ),
  ( 'Sweden', 'SWE', 'SEK' ),
  ( 'Australia', 'AUS', 'AUD' ),
  ( 'Cameroon', 'CMR', 'XAF' ),
  ( 'Ecuador', 'ECU', 'USD' ),
  ( 'Qatar', 'QAT', 'QAR' ),
  ( 'Marshall Islands', 'MHL', 'USD' ),
  ( 'Poland', 'POL', 'PLN' ),
  ( 'Cayman Islands', 'CYM', 'KYD' ),
  ( 'South Africa', 'ZAF', 'ZAR' ),
  ( 'Wallis and Futuna', 'WLF', 'XPF' ),
  ( 'Samoa', 'WSM', 'WST' ),
  ( 'Netherlands', 'NLD', 'EUR' ),
  ( 'Western Sahara', 'ESH', 'DZD' ),
  ( 'Montenegro', 'MNE', 'EUR' ),
  ( 'Bhutan', 'BTN', 'INR' ),
  ( 'Malta', 'MLT', 'EUR' ),
  ( 'Vanuatu', 'VUT', 'VUV' ),
  ( 'Tanzania', 'TZA', 'TZS' ),
  ( 'New Zealand', 'NZL', 'NZD' ),
  ( 'Palau', 'PLW', 'USD' ),
  ( 'Panama', 'PAN', 'PAB' ),
  ( 'Tuvalu', 'TUV', 'TVD' ),
  ( 'Fiji', 'FJI', 'FJD' ),
  ( 'Nicaragua', 'NIC', 'NIO' ),
  ( 'Kyrgyzstan', 'KGZ', 'KGS' ),
  ( 'French Southern and Antarctic Lands', 'ATF', 'EUR' ),
  ( 'Latvia', 'LVA', 'EUR' ),
  ( 'Georgia', 'GEO', 'GEL' ),
  ( 'Luxembourg', 'LUX', 'EUR' ),
  ( 'Austria', 'AUT', 'EUR' ),
  ( 'North Macedonia', 'MKD', 'MKD' ),
  ( 'Saint Barthélemy', 'BLM', 'EUR' ),
  ( 'Christmas Island', 'CXR', 'AUD' ),
  ( 'Solomon Islands', 'SLB', 'SBD' ),
  ( 'Antigua and Barbuda', 'ATG', 'XCD' ),
  ( 'Iraq', 'IRQ', 'IQD' ),
  ( 'Moldova', 'MDA', 'MDL' ),
  ( 'Norfolk Island', 'NFK', 'AUD' ),
  ( 'Republic of the Congo', 'COG', 'XAF' ),
  ( 'Niue', 'NIU', 'NZD' ),
  ( 'Lithuania', 'LTU', 'EUR' ),
  ( 'Niger', 'NER', 'XOF' ),
  ( 'Guyana', 'GUY', 'GYD' ),
  ( 'Bermuda', 'BMU', 'BMD' ),
  ( 'Gabon', 'GAB', 'XAF' ),
  ( 'Cook Islands', 'COK', 'CKD' ),
  ( 'Angola', 'AGO', 'AOA' ),
  ( 'Norway', 'NOR', 'NOK' ),
  ( 'Guadeloupe', 'GLP', 'EUR' ),
  ( 'Maldives', 'MDV', 'MVR' ),
  ( 'Belgium', 'BEL', 'EUR' ),
  ( 'Croatia', 'HRV', 'EUR' ),
  ( 'Belize', 'BLZ', 'BZD' ),
  ( 'Saint Kitts and Nevis', 'KNA', 'XCD' ),
  ( 'Singapore', 'SGP', 'SGD' ),
  ( 'Lesotho', 'LSO', 'LSL' ),
  ( 'Uruguay', 'URY', 'UYU' ),
  ( 'Burkina Faso', 'BFA', 'XOF' ),
  ( 'India', 'IND', 'INR' ),
  ( 'Philippines', 'PHL', 'PHP' ),
  ( 'Central African Republic', 'CAF', 'XAF' ),
  ( 'Sudan', 'SDN', 'SDG' ),
  ( 'Guinea-Bissau', 'GNB', 'XOF' ),
  ( 'Papua New Guinea', 'PNG', 'PGK' ),
  ( 'United States Minor Outlying Islands', 'UMI', 'USD' )
  ) AS SourceData (CountryName, CountryCode, Currency)
        WHERE NOT EXISTS (
            SELECT 1
            FROM Country c
            WHERE c.CountryCode = SourceData.CountryCode
);